version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: regexp_parser
    versions:
    - 2.0.3
    - 2.1.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: parser
    versions:
    - 3.0.0.0
  - dependency-name: ffi
    versions:
    - 1.14.2
  - dependency-name: bootsnap
    versions:
    - 1.6.0

