name: RSpec
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRES_USER: rubybot
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://rubybot:password@localhost:5432/ruby_bot_test
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: rubybot
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ruby_bot_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      #   with:
      #     ruby-version: 2.7.1
      - name: Set up Ruby version
        uses: ruby/setup-ruby@v1.106.0
        with:
          ruby-version: 3.1.2
          #bundler-cache: true
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      # - name: Cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle --without production
          yarn install

      - name: setup DB
        run: |
          bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
